import { Poppins } from "next/font/google";
import "./globals.css";
import "./fonts.css";
import { AuthProvider } from "./Context/AuthContext";
import NextTopLoader from "nextjs-toploader";
import CartProvider from "./redux/CartProvider";
import ReportButton from "./Components/ReportButton";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} font-poppins`}>
        <NextTopLoader
          showSpinner={false}
          color="#fbbf24"
          crawlSpeed={100}
          height={3}
        />
        <ReportButton/>
        <AuthProvider>
          <CartProvider>
          {children}</CartProvider></AuthProvider>
      </body>
    </html>
  );
}
